<a href="https://colab.research.google.com/github/uday-ctrl/hello-world/blob/master/Hiring.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("/content/drive/My Drive/machine learning/hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
df.experience = df.experience.fillna('zero')

In [5]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [7]:
!pip install word2number


  Created wheel for word2number: filename=word2number-1.1-cp36-none-any.whl size=5587 sha256=ce0d52d861a092d560954fe984a7daaed7afcb3c5eda90602d107209fb36f9da
  Stored in directory: /root/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [12]:
df.experience = df.experience.apply(w2n.word_to_num)

In [13]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [23]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test)

In [22]:
import math
median_test = math.floor(df['test_score(out of 10)'].median())

In [24]:
df

experience test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                     8                           9      50000
1           0                     8                           6      45000
2           5                     6                           7      60000
3           2                    10                          10      65000
4           7                     9                           6      70000
5           3                     7                          10      62000
6          10                     7                           7      72000
7          11                     7                           8      80000

In [26]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
reg.predict([[0,6,7]])

array([43352.8840088])

In [29]:
reg.predict([[2,9,6]])

array([53713.86677124])

In [30]:
reg.predict([[12,10,10]])

array([93747.79628651])